### ISSUE TITLE
请问怎么部署?

### ISSUE THREAD

**Issue by rising001** [chncaesar/hive-lineage-hook#2]

**Comment by huajianyihujiu** [comment]
run() 方法中的 if(value != null) {   }  里写上  System.out.println(value.toString());
然后打成jar包：HiveParseCDH-1.0-SNAPSHOT.jar ，放到服务器 /root/target/ 目录下
在 hive 命令行执行 ：
add jar /root/target/HiveParseCDH-1.0-SNAPSHOT.jar;
set hive.exec.post.hooks=zjc.hive.hooks.LineageHook;
然后可以执行hivesql，查看打印出来的信息，再根据需求进行下一步的代码修改。

**Comment by chncaesar** [comment]
Please read the READM.md, and rise an issue if you have any questions
